
project_id = "xragglavvbjmcwrtknrm"

[api]
realtime = true

[studio]
enabled = true

[db]
shadow_database_disabled = true

[db.hooks]
enabled = true

[realtime]
enabled = true

[realtime.channels]
bigbroadcast = { allowed_event="*", allowed_schema="public", allowed_tables=["completed_exercises"] }
