// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xragglavvbjmcwrtknrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyYWdnbGF2dmJqbWN3cnRrbnJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2ODg5ODIsImV4cCI6MjA2MTI2NDk4Mn0.gAlfYOkl9f2XpIjdP5jC352BoYG8lcTnVb6gXjZ_9Jw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);